---
name: jfa-go-build-docker
kind: pipeline
type: docker

steps:
    - name: build-deploy
      image: appleboy/drone-ssh
      volumes:
          - name: ssh_key
            path: /root/drone_rsa
      settings:
          host:
              from_secret: ssh2_host
          username:
              from_secret: ssh2_username
          port:
              from_secret: ssh2_port
          volumes:
              - /root/.ssh/docker-build:/root/drone_rsa
          key_path: /root/drone_rsa
          command_timeout: 50m
          script:
              - /mnt/buildx/jfa-go-build-docker/build.sh
trigger:
    event:
        - cron
        - push
volumes:
    - name: ssh_key
      host:
          path: /root/.ssh/docker-build
