when:
  - event: push
    branch: main

steps:
  - name: build
    image: docker.io/woodpeckerci/plugin-docker-buildx
    settings:
        username:
            from_secret: DOCKER_USERNAME
        password:
            from_secret: DOCKER_TOKEN
        repo: docker.io/hrfee/jfa-go-build-docker
        registry: docker.io
        platforms: linux/arm64
